version: "3.9"
services:
    mongo:
        image: mongo:4.4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${mongoUser}"
            MONGO_INITDB_ROOT_PASSWORD: "${mongoPassword}"
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "${mongoUser}"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "${mongoPassword}"
            ME_CONFIG_MONGODB_URL: "${mongo}"
    postgresdockerdashboard:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
    dashboard:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
            - 3002:3000
        volumes:
            - ./src:/app/src
            - ./build:/app/build
            - ./nodemon.json:/app/nodemon.json
        command: npm run devd --reload
volumes:
    mongo-data:
        driver: local
    postgres-data:
        driver: local
networks:
    default:
        external:
            name: gstreet
