
version: '3.9'
services:
    nginx:
        depends_on:
            - dashboard
        restart: always # because it is routing traffic to our entire app
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '80:80'
            - '443:443'
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${mongoUser}"
            MONGO_INITDB_ROOT_PASSWORD: "${mongoPassword}"
        ports: 
        - 27017:27017
        volumes: 
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "${mongoUser}"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "${mongoPassword}"
            ME_CONFIG_MONGODB_URL: "${mongo}"
    postgresdocker:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports: 
        - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
    dashboard:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 5000:5000
        - 3000:3000
        volumes:
            - ./src:/app/src
            - ./build:/app/build
            - ./nodemon.json:/app/nodemon.json
            - ./.env:/app/.env
        command: npm run dev
volumes:
    mongo-data:
        driver: local
    postgres-data:
        driver: local
