version: "3.9"
services:
    testPostgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5432:5432
    testmongo:
        image: mongo:4.4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${mongoUser}"
            MONGO_INITDB_ROOT_PASSWORD: "${mongoPassword}"
        ports:
            - 27017:27017
    testdashboard:
        build:
            context: .
            dockerfile: test.Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/app/
        command: node ./build/server/server.js
networks:
    default:
        external:
            name: gstreet-test
