version: "3.9"
services:
    dashboard:
        build:
            context: .
            dockerfile: build.Dockerfile
        volumes:
            - ./.env:/app/.env
        ports:
            - 5000:5000
        command: npm run start
