version: "3.9"
services:
    dashboard:
        build:
            context: .
            dockerfile: express.Dockerfile
        volumes:
            - ./.env:/app/.env
        ports:
            - 5000:5000
        command: node ./build/server/server.js
