version: "3.9"
services:
    dashboard:
        build:
            context: .
            dockerfile: build.Dockerfile
        volumes:
            - ./.env:/app/.env
        ports:
            - 5000:5000
            - 3002:3000
        command: concurrently "npx serve -s build" "node ./build/server/server.js"
