
version: '3.9'
services:
    testPostgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports: 
        - 5432:5432
    testdashboard:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 5000:5000
        volumes:
            - ./src:/app/src
            - ./build:/app/build
            - ./nodemon.json:/app/nodemon.json
            - ./mockdb.js:/app/mockdb.js