version: "3.9"
services:
    testdashboard:
        build:
            context: .
            dockerfile: test.Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/app/
networks:
    default:
        external:
            name: gstreet-test
